# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Sean Clancy
footer_text: >
  Theme Credit: <a href="https://github.com/alshedivat/al-folio">Maruan Al-Shedivat</a>.
  
# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: sean-clancy
# scholar_userid: # your Google Scholar ID
# orcid_id: # your ORCID ID

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"

theme: jekyll-theme-minimal